version: '3.2'

services:
  mysqldb:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: HeyDieei
      MYSQL_USER : utente
      MYSQL_PASSWORD: utente    
      
